nguage: ruby
cache: bundler

rbenv:
  - 2.1.2

script: 'bundle exec rspec'

notifications:
  slack: backer-founder:gS9GQrOqRKRogUEU5ajHYFZ9#crowd-trail
  email:
    recipients:
      - stan001212@gmail.com
  on_failure: change
  on_success: never
