language: ruby
cache: bundler

rvm:
  - 2.1.2

script: 'bundle exec rspec'

notifications:
  slack:
    rooms:
      - backer-founder:gS9GQrOqRKRogUEU5ajHYFZ9#crowd-trail
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
